package com.bplow.search.domain;

import java.util.Arrays;
import java.util.Date;

public class SrContent {
	
    private String id;

    private String cntCaption;

    private String secondCaption;

    private String operateUserId;

    private String isDeleteFlag;

    private Integer orderId;

    private Integer clickNum;

    private String catalogId;

    private Date gmtCreate;

    private Date gmtModify;

    private byte[] content;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getCntCaption() {
        return cntCaption;
    }

    public void setCntCaption(String cntCaption) {
        this.cntCaption = cntCaption == null ? null : cntCaption.trim();
    }

    public String getSecondCaption() {
        return secondCaption;
    }

    public void setSecondCaption(String secondCaption) {
        this.secondCaption = secondCaption == null ? null : secondCaption.trim();
    }

    public String getOperateUserId() {
        return operateUserId;
    }

    public void setOperateUserId(String operateUserId) {
        this.operateUserId = operateUserId == null ? null : operateUserId.trim();
    }

    public String getIsDeleteFlag() {
        return isDeleteFlag;
    }

    public void setIsDeleteFlag(String isDeleteFlag) {
        this.isDeleteFlag = isDeleteFlag == null ? null : isDeleteFlag.trim();
    }

    public Integer getOrderId() {
        return orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public Integer getClickNum() {
        return clickNum;
    }

    public void setClickNum(Integer clickNum) {
        this.clickNum = clickNum;
    }

    public String getCatalogId() {
        return catalogId;
    }

    public void setCatalogId(String catalogId) {
        this.catalogId = catalogId == null ? null : catalogId.trim();
    }

    public Date getGmtCreate() {
        return gmtCreate;
    }

    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public Date getGmtModify() {
        return gmtModify;
    }

    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    public byte[] getContent() {
        return content;
    }

    public void setContent(byte[] content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_content
     *
     * @mbggenerated Sat Oct 29 15:16:46 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SrContent other = (SrContent) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCntCaption() == null ? other.getCntCaption() == null : this.getCntCaption().equals(other.getCntCaption()))
            && (this.getSecondCaption() == null ? other.getSecondCaption() == null : this.getSecondCaption().equals(other.getSecondCaption()))
            && (this.getOperateUserId() == null ? other.getOperateUserId() == null : this.getOperateUserId().equals(other.getOperateUserId()))
            && (this.getIsDeleteFlag() == null ? other.getIsDeleteFlag() == null : this.getIsDeleteFlag().equals(other.getIsDeleteFlag()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getClickNum() == null ? other.getClickNum() == null : this.getClickNum().equals(other.getClickNum()))
            && (this.getCatalogId() == null ? other.getCatalogId() == null : this.getCatalogId().equals(other.getCatalogId()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModify() == null ? other.getGmtModify() == null : this.getGmtModify().equals(other.getGmtModify()))
            && (Arrays.equals(this.getContent(), other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_content
     *
     * @mbggenerated Sat Oct 29 15:16:46 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCntCaption() == null) ? 0 : getCntCaption().hashCode());
        result = prime * result + ((getSecondCaption() == null) ? 0 : getSecondCaption().hashCode());
        result = prime * result + ((getOperateUserId() == null) ? 0 : getOperateUserId().hashCode());
        result = prime * result + ((getIsDeleteFlag() == null) ? 0 : getIsDeleteFlag().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getClickNum() == null) ? 0 : getClickNum().hashCode());
        result = prime * result + ((getCatalogId() == null) ? 0 : getCatalogId().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModify() == null) ? 0 : getGmtModify().hashCode());
        result = prime * result + (Arrays.hashCode(getContent()));
        return result;
    }
}